### ISSUE TITLE
Ensure that updating the `status` doesn't trigger a reconcile

### ISSUE THREAD

**Issue by sbose78** [pedjak/rhthp-status-service-operator#11]
https://github.com/pedjak/rhthp-status-service-operator/blob/33f3e6793f01c7a8d7fb5b89cef626a26b8a4eb5/pkg/controller/statusservice/statusservice_controller.go#L168

By default any changes to the `spec` or `status` triggers a reconcile, how do we avoid that ?

**Comment by pedjak** [comment]
as stated in https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#status-subresource
` .metadata.generation` is not incremented on changes  to `.metadata` or `.status`
this behavior can be used to avoid additional reconciliations when only status got updated.

PR #14 provides the fix.

**Comment by pedjak** [comment]
Please close the issue if the solution in #14 matches the expectations.

**Comment by sbose78** [comment]
Exactly, predicate is indeed the answer. Good work!
