### ISSUE TITLE
Watch (indirectly) associated `pods`  

### ISSUE THREAD

**Issue by sbose78** [pedjak/rhthp-status-service-operator#12]
Was part of https://github.com/pedjak/rhthp-status-service-operator/issues/3

I'm actually looking to watch the `pods` too and trigger reconcile on the primary resource - I'm aware that the relationship is indirect.

Could you provide a fix for that, please?

**Comment by pedjak** [comment]
It was trickier than I thought :) the key ingredient is `handler.EnqueueRequestsFromMapFunc`. PR #13 provides the fix.

**Comment by pedjak** [comment]
Please close the issue if the solution matches the expectations.

**Comment by sbose78** [comment]
Looks good, thanks!
