### ISSUE TITLE
Differentiate between empty string and un-specified attribute

### ISSUE THREAD

**Issue by sbose78** [pedjak/rhthp-status-service-operator#2]
https://github.com/pedjak/rhthp-status-service-operator/blob/42f78d09473dcf948e53adae7f75924ce623673e/pkg/apis/app/v1alpha1/statusservice_types.go#L27

What would be a good way to define this variable such that we can programmatically understand if the attribute was unset or assigned to an empty variable?

**Comment by pedjak** [comment]
the variable should be declared like this:

```
Repository *string `json:"repository"`
```

having that, now we are in position to differ two situations:

* `Repository == nil`
* `len(*Repository) == 0`

PR #5 contains the fix.

**Comment by pedjak** [comment]
While working on #1 I have noticed that json tag must be

```
Repository *string `json:"repository,omitempty"
```

otherwise the generated openapi schema specifies them as required. PR #6 fixes it.

**Comment by pedjak** [comment]
After some extensive search through operator-sdk PRs and code, I have learned that the latest version (0.10.0) supports [kubebuilder marker](https://book.kubebuilder.io/reference/markers/crd-validation.html) that ensure correctness of openapi schema (without these markers, `nullable: true`) would disappear after invoking `operator-sdk generate openapi`. PR #8 fixes it.

**Comment by pedjak** [comment]
PR #10 added a fix for logging messages (they should be printed only when `Repository` or `Version` are really empty). Furthermore, I have noticed that `TestScaleUp` and `TestScaleDown` did not work - constructed image names were wrong. I was able to fix them by declaring `defaultRepository` and `defaultVersion` as constants. I am not so advanced with Go to understand the real cause for this effect.
